### PR TITLE
Update imports to use namespaces to be compatible with rn@0.40.0

### LINKED ISSUE #42: [Breaking] Header files moved with react-native@0.40.0
[react-native moved the header files starting with version 0.40.0](https://github.com/facebook/react-native/releases/tag/v0.40.0)

I'll create a PR to adjust the imports, could you have a look at this? Otherwise we are stuck on react-native 0.39.2.

Thanks,
Peter.

### PR DESCRIPTION
**Pull request by peterjuras**
Fixes #42

### CODE REVIEW

**Comment by frostney** [comment]
Thank you. This is amazing! 👍 
Let me just quickly test this for myself, because I don't believe I have any RN 0.40 projects yet.

**Comment by peterjuras** [comment]
Did you find time to test the PR yet?

**Review by jeffreyroshan — APPROVED** [review]
Please merge this.

**Review by skhameneh — APPROVED** [review]

**Comment by frostney** [comment]
I would prefer not to break backwards compatibility if we could avoid it. Would it be possible to update this PR to cater for this @peterjuras ?
I found a sensible approach to this here: https://medium.com/@thisismissem/how-to-upgrade-react-native-modules-in-a-backwards-compatible-manner-a5b5c48d590c#.ku4y0zjq3
What's your opinion on this?

**Comment by peterjuras** [comment]
Personally, I don't think it is worth it to hold up backwards compatibility, since react-native is still not out of beta and changing quickly.

Also, it appears that almost no react-native library has chosen to go with this path (I only saw Microsoft's code-push do these sorts of imports), therefore a lot of projects have to migrate anyways because big libraries (e.g. react-native-vector-icons, facebook's own react-native-fbsdk) did not migrate in a backwards compatible way.

However, this is your repo, therefore I leave the choice up to you. I created an [alternative pull request](https://github.com/frostney/react-native-ibeacon/pull/47) that imports the header with the way you described and it works for both 0.40 and 0.39. I don't recommend it though.

Feel free to choose any of the approaches.

**Comment by peterjuras** [comment]
Any update on the merging of a PR alternative?

**Comment by plbrault** [comment]
@frostney Any update?

**Comment by cahalane** [comment]
Please merge one of the options available! The iOS side of my app is being stalled by this.

**Comment by PeterKow** [comment]
Yes can we merge this? We are using it in our app with NR 42.3 and with those changes everything works nicely :) 👍

**Comment by leesolway** [comment]
Any news on this being merged?

**Comment by peterjuras** [comment]
I've since moved to [react-native-beacons-manager](https://github.com/MacKentoch/react-native-beacons-manager). It has a similar (or pretty much the same API) and works under iOS and Android with newer react-native versions.

I feel bad for "advertising" an alternative, but this might at least be something worthwhile to check out while this is being updated ...

**Comment by peterjuras** [comment]
Closed due to inactivity of repository.

**Pull request closed without merging**
